### ISSUE TITLE
Link to SVM medium article in Logistic Regression notebook is broken

### ISSUE THREAD

**Issue by abhayana24** [madewithml/basics#181]
Link to medium article on SVM in the logistic regression notebook is broken:

![image](https://user-images.githubusercontent.com/7872601/100537951-b0367c80-3252-11eb-89ca-476dcc2657ad.png)

![image](https://user-images.githubusercontent.com/7872601/100537987-e673fc00-3252-11eb-9d29-29682d4e1711.png)

**Comment by GokuMohandas** [comment]
Looks like the author who wrote that article has been banned.
